# Generated by Django 3.0.3 on 2020-03-03 14:45

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'Class'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='rollno',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.AddField(
            model_name='class',
            name='class_no',
            field=models.CharField(choices=[('11', '11'), ('12', '12')], default=9, max_length=2),
        ),
        migrations.AddField(
            model_name='class',
            name='dept',
            field=models.CharField(choices=[('Pre-Medical', 'Pre-Medical'), ('Pre-Engineering', 'Pre-Engineering'), ('Pre-Computer Science', 'Pre-Computer Science')], default='Bio', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='F-11, Markaz', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='classno',
            field=models.ForeignKey(default='9', on_delete=django.db.models.deletion.CASCADE, to='info.Class'),
        ),
        migrations.AddField(
            model_name='student',
            name='fee',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='fname',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AddField(
            model_name='teacher',
            name='address',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AddField(
            model_name='teacher',
            name='salary',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='class',
            name='section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='DOB',
            field=models.DateField(default='2005-01-01'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='DOB',
            field=models.DateField(default='1990-01-01'),
        ),
    ]
