# Generated by Django 3.0.3 on 2020-03-03 14:56

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20200303_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=128),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=128),
        ),
    ]
