# Generated by Django 3.0.3 on 2020-03-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20200303_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='shortname',
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('Botany', 'Botany'), ('Zoology', 'Zoology'), ('English', 'English'), ('Urdu', 'Urdu'), ('Pakistan-Studies', 'Pakistan-Studies'), ('Computer-Science', 'Computer-Science')], default='Mathematics', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('Botany', 'Botany'), ('Zoology', 'Zoology'), ('English', 'English'), ('Urdu', 'Urdu'), ('Pakistan-Studies', 'Pakistan-Studies'), ('Computer-Science', 'Computer-Science')], max_length=50),
        ),
    ]
