# Generated by Django 3.0.3 on 2020-03-03 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20200304_0247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={},
        ),
    ]
