# Generated by Django 3.0.3 on 2020-03-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_auto_20200306_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='ENG11', max_length=6),
            preserve_default=False,
        ),
    ]
