# Generated by Django 3.0.3 on 2020-03-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_auto_20200317_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='about',
            field=models.CharField(default='Hello', max_length=1000),
        ),
    ]
