# Generated by Django 3.0.3 on 2020-03-20 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_announcements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcements',
            name='activity',
        ),
        migrations.AddField(
            model_name='announcements',
            name='content',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcements',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='announcements',
            name='title',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
