# Generated by Django 3.0.3 on 2020-03-20 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0014_auto_20200320_1956'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Announcements',
            new_name='Announcement',
        ),
    ]
