# Generated by Django 3.0.3 on 2020-03-25 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_auto_20200320_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('Botany', 'Botany'), ('Zoology', 'Zoology'), ('English', 'English'), ('Urdu', 'Urdu'), ('Pakistan-Studies', 'Pakistan-Studies'), ('Computer-Science', 'Computer-Science')], default='Math', max_length=50),
        ),
        migrations.CreateModel(
            name='SubjectTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Teacher')),
            ],
        ),
    ]
