# Generated by Django 3.0.3 on 2020-03-27 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0022_auto_20200326_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Monthly Test', max_length=20)),
                ('total_marks', models.IntegerField(default=0)),
                ('obtained', models.FloatField(default=0)),
                ('classi', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='info.SubjectTeacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
