# Generated by Django 3.0.3 on 2020-04-05 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0023_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='date',
            field=models.DateField(default=datetime.date(2020, 4, 5)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('Botany', 'Botany'), ('Zoology', 'Zoology'), ('English', 'English'), ('Urdu', 'Urdu'), ('Physics', 'Physics'), ('Pakistan-Studies', 'Pakistan-Studies'), ('Computer-Science', 'Computer-Science')], default='Math', max_length=50),
        ),
    ]
