# Generated by Django 3.0.3 on 2020-04-05 16:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0024_auto_20200405_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('fee', models.IntegerField(default=0)),
                ('d_date', models.DateField(default=datetime.date(2020, 4, 5))),
                ('pay_date', models.DateField(default=datetime.date(2020, 4, 5))),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
