# Generated by Django 3.0.3 on 2020-04-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0026_auto_20200406_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'Sepember'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='March', max_length=10),
        ),
    ]
