# Generated by Django 3.0.3 on 2020-04-09 14:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0027_auto_20200406_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_time', models.TimeField()),
                ('e_time', models.TimeField()),
                ('classname', models.ForeignKey(default='9', on_delete=django.db.models.deletion.CASCADE, to='info.Class')),
            ],
        ),
        migrations.AlterField(
            model_name='fee',
            name='d_date',
            field=models.DateField(default=datetime.date(2020, 4, 9)),
        ),
        migrations.AlterField(
            model_name='fee',
            name='pay_date',
            field=models.DateField(default=datetime.date(2020, 4, 9)),
        ),
        migrations.AlterField(
            model_name='mark',
            name='date',
            field=models.DateField(default=datetime.date(2020, 4, 9)),
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classtime', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='info.Time')),
                ('subject', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='info.SubjectTeacher')),
            ],
        ),
    ]
