# Generated by Django 3.0.3 on 2020-04-09 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0029_auto_20200409_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='id',
        ),
        migrations.AlterField(
            model_name='timetable',
            name='classtime',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='info.Time'),
            preserve_default=False,
        ),
    ]
