# Generated by Django 3.0.3 on 2020-04-12 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0031_time_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.date(2020, 4, 12)),
        ),
        migrations.AlterField(
            model_name='fee',
            name='d_date',
            field=models.DateField(default=datetime.date(2020, 4, 12)),
        ),
        migrations.AlterField(
            model_name='fee',
            name='pay_date',
            field=models.DateField(default=datetime.date(2020, 4, 12)),
        ),
        migrations.AlterField(
            model_name='mark',
            name='date',
            field=models.DateField(default=datetime.date(2020, 4, 12)),
        ),
        migrations.AlterField(
            model_name='time',
            name='day',
            field=models.CharField(choices=[('Thursday', 'Thursday'), ('Saturday', 'Saturday'), ('Tuesday', 'Tuesday'), ('Friday', 'Friday'), ('Wednesday', 'Wednesday'), ('Monday', 'Monday')], default='Monday', max_length=20),
        ),
    ]
