# Generated by Django 3.0.3 on 2020-05-09 17:27

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0032_auto_20200412_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.date(2020, 5, 9)),
        ),
        migrations.AlterField(
            model_name='fee',
            name='d_date',
            field=models.DateField(default=datetime.date(2020, 5, 9)),
        ),
        migrations.AlterField(
            model_name='fee',
            name='pay_date',
            field=models.DateField(default=datetime.date(2020, 5, 9)),
        ),
        migrations.AlterField(
            model_name='mark',
            name='date',
            field=models.DateField(default=datetime.date(2020, 5, 9)),
        ),
        migrations.AlterField(
            model_name='student',
            name='fee',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='time',
            name='day',
            field=models.CharField(choices=[('Thursday', 'Thursday'), ('Saturday', 'Saturday'), ('Wednesday', 'Wednesday'), ('Tuesday', 'Tuesday'), ('Monday', 'Monday'), ('Friday', 'Friday')], default='Monday', max_length=20),
        ),
    ]
