# Generated by Django 3.0.3 on 2020-05-09 18:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0033_auto_20200509_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='salary',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='time',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Thursday', 'Thursday'), ('Saturday', 'Saturday'), ('Friday', 'Friday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday')], default='Monday', max_length=20),
        ),
    ]
