# Generated by Django 3.0.3 on 2020-05-09 19:01

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0035_auto_20200509_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.date(2020, 5, 10)),
        ),
        migrations.AlterField(
            model_name='fee',
            name='d_date',
            field=models.DateField(default=datetime.date(2020, 5, 10)),
        ),
        migrations.AlterField(
            model_name='fee',
            name='pay_date',
            field=models.DateField(default=datetime.date(2020, 5, 10)),
        ),
        migrations.AlterField(
            model_name='mark',
            name='date',
            field=models.DateField(default=datetime.date(2020, 5, 10)),
        ),
        migrations.AlterField(
            model_name='mark',
            name='obtained',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(500.0)]),
        ),
        migrations.AlterField(
            model_name='mark',
            name='total_marks',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(500.0)]),
        ),
        migrations.AlterField(
            model_name='time',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Saturday', 'Saturday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], default='Monday', max_length=20),
        ),
    ]
